### ISSUE TITLE
Creating users in system zone

### ISSUE THREAD

**Issue by hershsa** [Isilon/isilon_hadoop_tools#17]
Running into a couple issues when running the script against the system zone. 

If running with append-cluster-name option the script fails to add root-[cluster_name] to the proxy users since that user is never created. I'm guessing it really just wants to add root.

Then if I don't use the append-cluster-name option I get an error that the admin user and group already exist, which I believe is default to an Isilon cluster.

How best to fix these? I was thinking I can manually create the proxyuser:

Isiloncluster-1# isi hdfs proxyusers view --proxyuser=root
   Name: root
Members: ambari-qa
         hadoop

**Comment by dmtucker** [comment]
I think the `admin` issue may be fixed (#7), but the `root` issue is still relevant:
```
# ./isilon_create_users.sh --dist hwx --append-cluster-name clustername
Info: Hadoop distribution:  hwx
Info: will add clustername to end of usernames: -clustername
Info: HDFS root:  /ifs/hdfs
Info: passwd file: System.passwd
Info: group file: System.group
The Name root-clustername is not resolvable
ERRORS FOUND:
*  ERROR:  Could not create proxyuser root-clustername in zone System
FATAL:  ERRORS FOUND making Hadoop users in zone System -- please fix before continuing
```
