### ISSUE TITLE
issue with sqoop and duplicate sqoop & sqoop2 groups 

### ISSUE THREAD

**Issue by brittup** [Isilon/isilon_hadoop_tools#29]
ran script, saw issues with sqoop & sqoop2 groups, looks like its creating those groups twice, the group file outputted has them in their twice.

isilon01-1# bash isilon_create_users.sh --dist cdh --startuid 501 --startgid 501  --zone testzone
Info: Hadoop distribution:  cdh
Info: users will start at UID 501
Info: groups will start at GID 501
Info: will put users in zone:  testzone
Info: HDFS root:  /ifs/testzone
Info: passwd file: testzone.passwd
Info: group file: testzone.group
**sed: 1: "/sqoop:**x**:523:": unterminated regular expression**
SUCCESS -- Hadoop users created successfully!

Done!
isilon01-1# ls -al
total 137
drwxr-xr-x    2 root  wheel    356 Mar  9 10:27 .
drwxr-xr-x    5 root  wheel     76 Mar  8 17:04 ..
-rwxr--r--    1 root  wheel    151 Mar  8 17:56 creategroups.sh
-rwxr--r--    1 root  wheel    452 Mar  8 17:51 createusers.sh
-rwxr--r--    1 root  wheel  10028 Mar  8 17:04 isilon_create_directories.sh
-rwxr--r--    1 root  wheel  11593 Mar  8 17:04 isilon_create_users.sh
-rwxr--r--    1 root  wheel    560 Mar  8 17:39 zone1-cdh.group
-rwxr--r--    1 root  wheel    553 Mar  8 17:39 zone1-cdh.group.bak
-rwxr--r--    1 root  wheel   1643 Mar  8 17:39 zone1-cdh.passwd

isilon01-1# cat testzone.passwd
use this file to add to the passwd file of your clients
hdfs:**x**:501:501:hadoop-svc-account:/home/hdfs:/bin/bash
mapred:**x**:502:502:hadoop-svc-account:/home/mapred:/bin/bash
yarn:**x**:503:503:hadoop-svc-account:/home/yarn:/bin/bash
HTTP:**x**:504:504:hadoop-svc-account:/home/HTTP:/bin/bash
hbase:**x**:505:505:hadoop-svc-account:/home/hbase:/bin/bash
hive:**x**:506:506:hadoop-svc-account:/home/hive:/bin/bash
impala:**x**:507:507:hadoop-svc-account:/home/impala:/bin/bash
hue:**x**:508:508:hadoop-svc-account:/home/hue:/bin/bash
cloudera-scm:**x**:509:509:hadoop-svc-account:/home/cloudera-scm:/bin/bash
accumulo:**x**:510:510:hadoop-svc-account:/home/accumulo:/bin/bash
flume:**x**:511:511:hadoop-svc-account:/home/flume:/bin/bash
httpfs:**x**:512:512:hadoop-svc-account:/home/httpfs:/bin/bash
apache:**x**:513:513:hadoop-svc-account:/home/apache:/bin/bash
kafka:**x**:514:514:hadoop-svc-account:/home/kafka:/bin/bash
kms:**x**:515:515:hadoop-svc-account:/home/kms:/bin/bash
keytrustee:**x**:516:516:hadoop-svc-account:/home/keytrustee:/bin/bash
kudu:**x**:517:517:hadoop-svc-account:/home/kudu:/bin/bash
llama:**x**:518:518:hadoop-svc-account:/home/llama:/bin/bash
oozie:**x**:519:519:hadoop-svc-account:/home/oozie:/bin/bash
solr:**x**:520:520:hadoop-svc-account:/home/solr:/bin/bash
spark:**x**:521:521:hadoop-svc-account:/home/spark:/bin/bash
sentry:**x**:522:522:hadoop-svc-account:/home/sentry:/bin/bash
sqoop:**x**:523:523:hadoop-svc-account:/home/sqoop:/bin/bash
sqoop2:**x**:524:524:hadoop-svc-account:/home/sqoop2:/bin/bash
zookeeper:**x**:525:525:hadoop-svc-account:/home/zookeeper:/bin/bash
anonymous:**x**:526:526:hadoop-svc-account:/home/anonymous:/bin/bash
cmjobuser:**x**:527:527:hadoop-svc-account:/home/cmjobuser:/bin/bash

isilon01-1 cat testzone.group
use this file to add to the group file of your clients
hdfs:**x**:501:
mapred:**x**:502:
yarn:**x**:503:
HTTP:**x**:504:
hbase:**x**:505:
impala:**x**:507:
hue:**x**:508:
cloudera-scm:**x**:509:
accumulo:**x**:510:
flume:**x**:511:
httpfs:**x**:512:
apache:**x**:513:
kafka:**x**:514:
kms:**x**:515:
keytrustee:**x**:516:
kudu:**x**:517:
llama:**x**:518:
oozie:**x**:519:
solr:**x**:520:
spark:**x**:521:
sentry:**x**:522:
**sqoop:**x**:523:**
**sqoop2:**x**:524:**
zookeeper:**x**:525:
anonymous:**x**:526:
cmjobuser:**x**:527:
hadoop:**x**:528:,hdfs,mapred,yarn,HTTP,hbase
supergroup:**x**:529:,hdfs,mapred,yarn,HTTP,hbase
**sqoop:**x**:523:**
**sqoop2:**x**:524:,sqoop2**
hive:**x**:506:,impala

**Comment by dmtucker** [comment]
This is likely due to #27.

**Comment by bonibruno** [comment]
See PR bonibruno-patch3.

**Comment by bonibruno** [comment]
Fix in PR #32.  This will be merged soon.
