### ISSUE TITLE
missing group memberships CDH 5.10

### ISSUE THREAD

**Issue by brittup** [Isilon/isilon_hadoop_tools#30]
Using the outputted group & group membership from script execution. The cloudera installer complained about the following two omissions.

sqoop2 user not in sqoop group
impala user is not hive group

![image](https://cloud.githubusercontent.com/assets/10853314/23810842/1bcc5c22-0588-11e7-96de-6a3df5e958c6.png)

sqoop2 in sqoop is missing from the group file
impala present, so unclear why cloudera manager complained, added manually and the issue went away

isilon01-1 cat zone1-cdh.group

use this file to add to the group file of your clients
hdfs:**x**:501:
mapred:**x**:502:
yarn:**x**:503:
HTTP:**x**:504:
hbase:**x**:505:
impala:**x**:507:
hue:**x**:508:
cloudera-scm:**x**:509:
accumulo:**x**:510:
flume:**x**:511:
httpfs:**x**:512:
apache:**x**:513:
kafka:**x**:514:
kms:**x**:515:
keytrustee:**x**:516:
kudu:**x**:517:
llama:**x**:518:
oozie:**x**:519:
solr:**x**:520:
spark:**x**:521:
sentry:**x**:522:
sqoop:**x**:523:
sqoop2:**x**:524:
zookeeper:**x**:525:
anonymous:**x**:526:
cmjobuser:**x**:527:
hadoop:**x**:528:,hdfs,mapred,yarn,HTTP,hbase
supergroup:**x**:529:,hdfs,mapred,yarn,HTTP,hbase
sqoop:**x**:523:
sqoop2:**x**:524:,sqoop2
hive:**x**:506:,impala

**Comment by dmtucker** [comment]
> sqoop2 in sqoop is missing from the group file

This looks like #27.

> impala present, so unclear why cloudera manager complained, added manually and the issue went away

This is interesting... It looks like only `centos-03` was affected whereas the sqoop issue affected `[01-03]`. How did you add `hive` to `impala` manually (i.e. editing the group file or via `usermod`)?

**Comment by brittup** [comment]
ah good catch, i must have been experimenting somehow.

pretty sure this is invalid now.

closing!
