### ISSUE TITLE
create yarn-ats user for HDP 3.0

### ISSUE THREAD

**Issue by ro-ket** [Isilon/isilon_hadoop_tools#49]
It's not mentioned in the Ambari 2.7 user/group list https://docs.hortonworks.com/HDPDocuments/Ambari-2.6.0.0/bk_ambari-administration/content/defining_service_users_and_groups_for_a_hdp_2x_stack.html

However Yarn Timeline Server needs this account in our experience. Also it is mentioned in this guide, https://docs.hortonworks.com/HDPDocuments/HDP3/HDP-3.0.0/data-operating-system/content/dosg_timeline_service_2.0_installation.html

**Comment by bonibruno** [comment]
See bonibruno-patch-1
