### ISSUE TITLE
How to migrate Cloudera HDFS to Isilon

### ISSUE THREAD

**Issue by imYerik** [Isilon/isilon_hadoop_tools#51]
We have a CDH cluster which has run for a long time, there's a lot of data stored on CDH HDFS.
How to migrate to Isilon HDFS, and replace CDH HDFS with Isilon?  Isilon document is just for new CDH configuration.
Any migration reference?

Thanks!

**Comment by dmtucker** [comment]
I am not currently aware of a guide for this, unfortunately. Are any features in use that Isilon does not yet support (e.g. [TDE](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/TransparentEncryption.html))? If not, you might consider using [DistCp](https://hadoop.apache.org/docs/current/hadoop-distcp/DistCp.html).
