### ISSUE TITLE
create yarn-ats-hbase user for HDP 3.0

### ISSUE THREAD

**Issue by kiran4t4t** [Isilon/isilon_hadoop_tools#53]
Even though it is not mentioned in the Ambari 2.7.1 users/group list, still need this user/group on OneFS for the cluster to function properly after kerberization.

Handling the user/group is easier than renaming the service principal for this one.

**Comment by bonibruno** [comment]
Just created a pull request for this, should be resolved soon...

**Comment by ro-ket** [comment]
Fixed by #54.
