### ISSUE TITLE
Add hawq user gpadmin

### ISSUE THREAD

**Issue by ro-ket** [Isilon/isilon_hadoop_tools#57]
The HWX distribution should have user `gpadmin` added. That is required by the optional HAWQ component.

When this isn't present, many authorization errors can be seen in logs. Below is an example from 8.1.2. In 8.0.0.7 errors were observed including LeaseExpiredException, FileNotFoundExecption, etc:
```
[hdfs] RPC V9  user: gpadmin exception: org.apache.hadoop.security.authorize.AuthorizationException cause: Username: 'gpadmin' not found. Make sure your client's username exists on the cluster
```

**Comment by dmtucker** [comment]
Resolved by #58
