### ISSUE TITLE
Create_Directories OneFS 8.2.2 API issue

### ISSUE THREAD

**Issue by toeknee182** [Isilon/isilon_hadoop_tools#78]
Running the isilon_create_directories.py script on OneFS 8.2.2 gets interrupted with the following error:

[DEBUG] response body:
{
"errors" :
[

{
"code" : "AEC_NOT_FOUND",
"message" : "Path not found: /4/protocols/hdfs/settings."
}
]
}

[ERROR] Path not found: /4/protocols/hdfs/settings.

**Comment by toeknee182** [comment]
I tried it and if we remove the /4/ from the call or replace the /4 with /9 it works.  I am not sure where in the code that is.

**Comment by tucked** [comment]
@toeknee182 That is correct. The handler has been updated in 8.2.2, and the fix will be to integrate `isi-sdk-8-2-2` when it is available.

**Comment by tucked** [comment]
`isi-sdk-8-2-2` was released earlier today: https://pypi.org/project/isi-sdk-8-2-2/

**Comment by toeknee182** [comment]
Thanks.  I will retest.
